before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test

python2:
  stage: test
  image: "python:2"
  script: 
    - python setup.py test
  except:
    - master
    - staging
  tags:
     - l1-max-solutions-co

python3:
  stage: test
  image: "python:3"
  script: 
    - python setup.py test
  except:
    - master
    - staging
  tags:
     - l1-max-solutions-co

python35:
  stage: test
  image: "python:3.5"
  script: 
    - python setup.py test
  except:
    - master
    - staging
  tags:
     - l1-max-solutions-co
     
python37:
  stage: test
  image: "python:3.7"
  script: 
    - python setup.py test
  except:
    - master
    - staging
  tags:
     - l1-max-solutions-co
